### ISSUE TITLE
Tow release detection

### ISSUE THREAD

**Issue by Turbo87** [xiadz/igc_lib#46]
I've just discovered your interesting library and was wondering if you considered implementing a detection for when a glider is being towed by plane (or winch). would that be possible using the same sort of algorithms?

**Comment by marcin-osowski** [comment]
That should be possible, and should help with the quality of the data (i.e. no thermals should be marked during launch). Smoothing and general behaviour (i.e. glider log almost always starts on the ground, then enters towing/launch phase, then enters free flight) can be expressed as a Markov chain.

Not sure how to capture the glider release moment, maybe a combination of vertical velocity and heading change? I.e. stay in launch mode if still going up, and all the turns are not very tight.
