### ISSUE TITLE
Glide alt_change() is wrong

### ISSUE THREAD

**Issue by llauner** [xiadz/igc_lib#53]
In the Glide class we have:
def alt_change(self):
        """Return the overall altitude change in the glide, meters."""
        return self.enter_fix.alt - self.exit_fix.alt

It should be return  self.exit_fix.alt - self.enter_fix.alt
So that it does reflect climbs (positive value) and sinks (negative values)

**Comment by marcin-osowski** [comment]
Thanks, fairly embarassing :0

Fixed in 14d683768e5f970abf612e978ed8ad98013d6d0d

**Comment by llauner** [comment]
No problem ! :)

You're library is great and I've forked it to create a thermal heatmap.
The result is here:
https://llauner.github.io/heatmapWeb/

I would now like to enrich it to be able to detect "sink glides" in the
form of a list of "lines" a line being 2 points.
I'd like to detect the lines were the sink rate is <= x m/s (let's say -1.5
m/s)

Now...my math years are long gone, and I'm not sure how to do this ?
Just looking at the start and end of a glide doesn't work of course.

Would you know how to do this ? I guess that wouild involve some matrix
calculation of some sort...

Regards
Ludovic

---
Ludovic Launer
ludovic@launer.fr
